# Generated by Django 4.1.2 on 2022-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_page_like_page_photo_page_post_page_video_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
