# Generated by Django 4.1.2 on 2022-10-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_page_active'),
        ('accounts', '0015_remove_account_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pages',
            field=models.ManyToManyField(blank=True, to='profiles.page'),
        ),
    ]
